### ISSUE TITLE
Wrong assumption about "_Z" prefix

### ISSUE THREAD

**Issue by loquens** [afg984/python-cxxfilt#1]
for example, N3foo12BarExceptionE is mangled foo::BarException

**Comment by afq984** [comment]
Which compiler are you using?
`c++filt` from GNU binutils does not recognize `N3foo12BarExceptionE`

**Comment by loquens** [comment]
> Which compiler are you using?

For example, g++-5
```
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Also g++-6, g++-7.

> c++filt from GNU binutils does not recognize N3foo12BarExceptionE

It does not, but abi::__cxa_demangle function from cxxabi.h easily demangles this name. So does the binding libcxx.__cxa_demangle

**Comment by jeffgarrett** [comment]
I ran into this bug as well. As an example, gcc produces the following mangled type name `Z4mainEUlvE_` (starts with `Z`, not `_Z`) and GNU binutils can demangle it as can `abi::__cxa_demangle`:

    $ c++filt -t Z4mainEUlvE_
    main::{lambda()#1}
    $ c++filt -version
    GNU c++filt (GNU Binutils) 2.31.1

You can see in the [mangling implementation](https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/gcc/cp/mangle.c#L2009) that function-scope names start with `Z`. It is external names that start with `_Z`.

**Comment by afq984** [comment]
As per the man page

```
$ c++filt -t a
signed char
```

I think this would break someone else's code.
Would adding a keyword argument work for you?

**Comment by jeffgarrett** [comment]
> Would adding a keyword argument work for you?

Yes, that'd be suitable for my use. Thanks so much!

**Comment by afq984** [comment]
`0.2.0` uploaded to pypi
