### ISSUE TITLE
Support demangling explicitly with clang vs gcc

### ISSUE THREAD

**Issue by pombredanne** [afg984/python-cxxfilt#8]
It would be great to explicitly ask for a certain demangling service (and fail if it is not found) as a follow up to  https://github.com/atlas0fd00m/python-cxxfilt/commit/c7f9d6c63969de7c50b2fc6c941dc40981d873ab from @atlas0fd00m

**Comment by afq984** [comment]
@pombredanne please see if the API in #9 looks OK. You can see the updated README [here](https://github.com/afq984/python-cxxfilt/tree/t3a11799d-8082-4b5e-accf-71dbdaa196a3)

**Comment by pombredanne** [comment]
Looking great! thank you ++ :heart_decoration:
